### ISSUE TITLE
why is this better than type someKey struct{}?

### ISSUE THREAD

**Issue by rogpeppe** [cstockton/go-ctxkey#1]
A common idiom for context keys is to use an
empty struct type:

   type appKey struct{}

Then there's no code and no overhead at all.
What's the advantage of using go-ctxkey over this?

**Comment by cstockton** [comment]
Hi @rogpeppe, First ill say there is not a huge advantage to using this library, it's mostly for informational purposes and to advocate a small design pattern I like for context keys. But it does have some advantages against the common pattern displayed on the official blog and possibly the pattern you have above. I display some in the [godoc](https://godoc.org/github.com/cstockton/go-ctxkey) examples.

The number 1 reason for me is for clarity in my API, which EXTRA useful if your ctx keys are public, but I think even private keys offer documentation clarity by being defined in a single location with no types required, i.e.:
```Go
var (
    AppKey  = appKey{}
    LogKey  = appLogKey{}
    AuthKey = appAuthKey{}
    UserKey = appUserKey{}
)
```

VS
```Go
var (
    AppKey  = ctxkey.New(`mypkg.App`)
    LogKey  = ctxkey.New(`mypkg.App.Log`)
    AuthKey = ctxkey.New(`mypkg.App.Auth`)
    UserKey = ctxkey.New(`mypkg.App.User`)
)

The first one to a inexperienced user may look like something they shouldn't fiddle with, it's private and even if it wasn't it doesn't look very "external", seems like a private package detail. You have to advertise it's purpose with documentation, the second one feels much more like something that is meant to be consumed.

Now if you are exposing multiple keys you have to pollute your namespace with multiple types. This is because you can't issue a context key pointing to a empty struct, all empty structs no matter what the type or indirection share the same address, so we need to make them a distinct type to force our inequality invariant. This isn't a problem for pointers to `type appKeyNamed struct{ Name string }` which each need a distinct allocation because they may are not immutable like an empty struct.

I.e.:
```Go
fmt.Printf("%p same address of %p and %p", &appKey{}, &appLogKey{}, &struct{}{})
```

So the no code statement becomes a bit less true when you have multiple context keys, since you need unique type definitions for each one and the actual variable to store a value of it, and gofmt has it's way with spacing. It's subjective of course, but I find the below ugly:

```Go
type appKey{} struct{}

type appAuthKey{} struct{}

type appLogKey{} struct{}

type appUserKey{} struct{}
```

Then there is the troubleshooting aspect, by naming your key and having a string method you are able to give it some sort of identifier of your choosing, it's unfortunate that context.Value uses %#v by default without checking for Stringer(), but the formatting of context values isn't fun to digest by default.

Finally I don't think there is any overhead to consider here, given the usage characteristics of create-once and reuse for context keys.. we are talking 4-6 allocations at your packages initialization. If by overhead you mean key usage, which you do many times through the lifespan of your app and it's an important metric.. they are identical. Neither requires more, or less work. Both are better than using `type ctxKey int`, which causes allocations.

So it all boils down to if you think having no type declarations and a subjectively cleaner API / logical grouping of your keys is worth using this pattern or not if you are already aware of the statements above. For gophers who have not dived these details, using this pattern prevents them from accidental misuse. 

Thanks for the question, hopefully I answered it, feel free to close this at your discretion, happy coding man.

**Comment by cstockton** [comment]
Close button fail. :- )

**Comment by rogpeppe** [comment]
Thanks for the reply. I find it interesting to discuss this area as context.Context
is so new and I think we're all feeling our way towards good idioms.

> It's subjective of course, but I find the below ugly:

	type (
		AppKey     struct{}
		AppAuthKey struct{}
		AppLogKey  struct{}
		AppUserKey struct{}
	)

looks very similar to:

    var (
        AppKey  = ctxkey.New(`mypkg.App`)
        LogKey  = ctxkey.New(`mypkg.App.Log`)
        AuthKey = ctxkey.New(`mypkg.App.Auth`)
        UserKey = ctxkey.New(`mypkg.App.User`)
    )

to me, only a little cleaner.

Because there's a separate type for each one, there's no possibility
of the keys being inadvertently (or deliberately!) assigned to.

That said, it's a pity that %#v doesn't print the whole package path,
as the "somepackage" in "...WithValue(somepackage.someKey{}, ...)"
can be ambiguous. Then again if someone clones your package
and forgets to change the strings, you'll have the same problem.

> Now if you are exposing multiple keys you have to pollute your namespace with multiple types.

AFAICS the namespace is just as "polluted" by variables as types - the same number of names are used.

> If by overhead you mean key usage, which you do many times through the lifespan of your app and it's an important metric.. they are identical.

It's just possible that a interface{}(struct{}{}) has less overhead than interface{}(&something) as there's no pointer to put in the struct and therefore less GC scanning to do, but I agree the overhead of both is minimal.

FWIW I almost never export context keys. Instead I provide one or two helper functions for each key:

   func AppFromContext(ctx context.Context) *App { 
       app, _ := ctx.Value(appKey{}).(*App)
       return app
   }

   func ContextWithApp(ctx context.Context, app *App) context.Context {
       return context.WithValue(ctx, appKey{}, app)
   }

That way the user doesn't have to worry about remembering the correct key-type
association, and there's no danger of someone associating the wrong type
of value with the key.

It's not uncommon to provide one without the other depending on whether the
package or the client is the one that is adding the context.

Thanks for providing food for thought. Until you pointed it out, I hadn't even observed
that context.Context implementations usually implement a String method!

**Comment by cstockton** [comment]
Hi, thanks for the reply. I actually like the grouped declaration for the context keys, it's not too bad looking for private usage. I think it's debatable about exposing context keys to users, I don't feel strongly either way. I tend to expose basic types like int, string, etc in literal keys to save them having to call a function, for structured types I think your pattern works great.

For the var argument, you definitely don't want to do what you are doing above, specially if you care about performance characteristics. It's not immediately apparent perhaps, but these two programs have different intrinsics leading to much to much different programs, despite it being a single instruction! Leaving a small bit of room for error on part (bench, profile and inspect ASM to get real numbers if you would like).

```Go
var appKeyVar = appKey{} // universe scope
return context.WithValue(ctx, appKeyVar, app)
```

```Go
return context.WithValue(ctx, appKey{}, app)
```

 The first one will be a simple load & move, however the second will be forced to autotmp because it's a struct literal, this is the same operation that happens when you declare `var Foo = struct{}{}`. This is tricky because it won't show up when trying to profile with AllocsPerRun like in my examples, I probably should have included this information in my examples. So why does this detail matter if it's not a alloc? Well it's work on the GC, you will need pages for the gc allocator on the heap, it will be a subtle divergence in the runtime garbage cycle for alloc spans of heap space and the work of managing them. Depending on how busy your GC is doing other things, or if it is doing other things at all I would take a wild guess at 15-30% slowdown.

Little things like above is why I made the package though, if nothing else at least someone who is interested in these tiny details can google it and I may help. Have a good one!

**Comment by rogpeppe** [comment]
> The first one will be a simple load & move, however the second will be forced to autotmp because it's a struct literal

Fascinating! I had no idea that those two would generate different code. I presumed that empty structs were more efficiently converted to interfaces than they are. I just raised an issue about this: https://github.com/golang/go/issues/18402

I made a little example program that shows all the different variants so that it's easy to compare the assembly output: https://play.golang.org/p/5DekbLS05E

That indicates that your package's keys would be a tiny bit more efficient if ctxkey.New returned interface{} or a static pointer type rather than Key.

So... *if* issue 18402 were fixed, then I believe that using an empty struct literal would probably be more efficient, as it could just load a literal zero. I think I'll continue to use that idiom for the time being unless I see measurable overhead from it as I think a named empty struct type is a very elegant representation of a singleton value.

> Well it's work on the GC, you will need pages for the gc allocator on the heap, it will be a subtle divergence in the runtime garbage cycle for alloc spans of heap space and the work of managing them. Depending on how busy your GC is doing other things, or if it is doing other things at all I would take a wild guess at 15-30% slowdown.

An extra slot on the stack incurs 15-30% slowdown? That seems a little unlikely to me - I'll have to think about how it might be possible to measure it.

BTW, if you don't like the way that your context keys print, you could always implement GoString to make them format more nicely.

This has been a very interesting diversion, thanks!

**Comment by cstockton** [comment]
I believe the performance differences I mention are due to workload on the GC. This workload is not related to the representation of the values when assigned to an interface, it's how (lifecycle of) they are assigned. The efficiency of `interface{}(struct{}{})` is as efficient as `interface{}((*int)(nil))` for assignment operations. Both will reuse the same address each time, meaning this is unrelated to #17725. The issue here is the GC has to take ownership when `type TypKey struct{}` is moved to the heap. This may be easier explained in a butchered SSA form.

When using a struct literal such as `context.WithValue(ctx, TypKey{}, val)`.
```Go
t1 = local TypKey
t2 = *t1
t3 = make interface{} <- t2
t4 = context.WithValue(t0, t3, ...)
```

When using an addressable value on the heap, context.WithValue(ctx, VarKey, val)`.
```
t1 = *VarKey (TypKey)
t2 = make interface{} <- t1
t3 = context.WithValue(t0, t2, ...)
```

I can't think of a way this could be avoided without a SSA pass that detects empty composite literals and allocates a single address for each T in a scratch space, only when T is a empty struct. I may be way off here, but I wanted to clarify a bit.

**Comment by rogpeppe** [comment]
> Not really, they will have near identical runtime characteristics. 

I made the remark based on looking at the actual instructions generated.
There were a couple of extra instructions (including a branch) in one case.
"Near identical" is probably correct though - I think it's unlikely that you'll
notice any of this stuff in practice, because none of it adds to GC pressure
and Context.Value calls probably aren't *that* much of a bottleneck.

> It would be a rather aggressive and tricky optimization that would only be possible for a T which is empty struct{} composite literal values.

This optimization is already done to an extent - there is only one address for all zero-sized objects. But you've already seen @randall77's comments in issue 18402.

I'll close this issue now, as there is still a potential performance advantage to be gained from using this package until 18402 is fixed. I'm glad I raised it though - this has been enlightening!
